/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 65
#line 1 "./Parser/parser.leg"

#ifndef PARSER_C
#define PARSER_C

#include <stdlib.h>
#include <string.h>
#include "parser.h"

#define YYSTYPE oop
YYSTYPE result;

#define YY_FREE(C, P) P = NULL

oop parserRetFlags[2] = {
	MAKE_OOP_FLAG(PARSER_FINISH),
	MAKE_OOP_FLAG(PARSER_ERROR),
};

static int nlines = 0;
//LEG AREA

#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_newline(yycontext *yy); /* 65 */
YY_RULE(int) yy_blank(yycontext *yy); /* 64 */
YY_RULE(int) yy_alnum(yycontext *yy); /* 63 */
YY_RULE(int) yy_alpha(yycontext *yy); /* 62 */
YY_RULE(int) yy_mkArray(yycontext *yy); /* 61 */
YY_RULE(int) yy_array(yycontext *yy); /* 60 */
YY_RULE(int) yy_integer(yycontext *yy); /* 59 */
YY_RULE(int) yy_RBRAK(yycontext *yy); /* 58 */
YY_RULE(int) yy_LBRAK(yycontext *yy); /* 57 */
YY_RULE(int) yy_MMINUS(yycontext *yy); /* 56 */
YY_RULE(int) yy_PPLUS(yycontext *yy); /* 55 */
YY_RULE(int) yy_PLING(yycontext *yy); /* 54 */
YY_RULE(int) yy_postfix(yycontext *yy); /* 53 */
YY_RULE(int) yy_PCENT(yycontext *yy); /* 52 */
YY_RULE(int) yy_SLASH(yycontext *yy); /* 51 */
YY_RULE(int) yy_STAR(yycontext *yy); /* 50 */
YY_RULE(int) yy_prefix(yycontext *yy); /* 49 */
YY_RULE(int) yy_MINUS(yycontext *yy); /* 48 */
YY_RULE(int) yy_PLUS(yycontext *yy); /* 47 */
YY_RULE(int) yy_mul(yycontext *yy); /* 46 */
YY_RULE(int) yy_LESS(yycontext *yy); /* 45 */
YY_RULE(int) yy_LESSEQ(yycontext *yy); /* 44 */
YY_RULE(int) yy_GREATEQ(yycontext *yy); /* 43 */
YY_RULE(int) yy_GREATER(yycontext *yy); /* 42 */
YY_RULE(int) yy_add(yycontext *yy); /* 41 */
YY_RULE(int) yy_NOTEQ(yycontext *yy); /* 40 */
YY_RULE(int) yy_EQUAL(yycontext *yy); /* 39 */
YY_RULE(int) yy_ineq(yycontext *yy); /* 38 */
YY_RULE(int) yy_RET(yycontext *yy); /* 37 */
YY_RULE(int) yy_FOR(yycontext *yy); /* 36 */
YY_RULE(int) yy_WHILE(yycontext *yy); /* 35 */
YY_RULE(int) yy_ELSE(yycontext *yy); /* 34 */
YY_RULE(int) yy_expr(yycontext *yy); /* 33 */
YY_RULE(int) yy_IF(yycontext *yy); /* 32 */
YY_RULE(int) yy_SEMI(yycontext *yy); /* 31 */
YY_RULE(int) yy_args(yycontext *yy); /* 30 */
YY_RULE(int) yy_PRINT(yycontext *yy); /* 29 */
YY_RULE(int) yy_index(yycontext *yy); /* 28 */
YY_RULE(int) yy_value(yycontext *yy); /* 27 */
YY_RULE(int) yy_assignment(yycontext *yy); /* 26 */
YY_RULE(int) yy_ASSIGN(yycontext *yy); /* 25 */
YY_RULE(int) yy_FUNC(yycontext *yy); /* 24 */
YY_RULE(int) yy_RPAR(yycontext *yy); /* 23 */
YY_RULE(int) yy_COMMA(yycontext *yy); /* 22 */
YY_RULE(int) yy_eqop(yycontext *yy); /* 21 */
YY_RULE(int) yy_mkFalse(yycontext *yy); /* 20 */
YY_RULE(int) yy_mkNil(yycontext *yy); /* 19 */
YY_RULE(int) yy_LPAR(yycontext *yy); /* 18 */
YY_RULE(int) yy_block(yycontext *yy); /* 17 */
YY_RULE(int) yy_eparams(yycontext *yy); /* 16 */
YY_RULE(int) yy_stt_local_assignment(yycontext *yy); /* 15 */
YY_RULE(int) yy_event(yycontext *yy); /* 14 */
YY_RULE(int) yy_RBRACE(yycontext *yy); /* 13 */
YY_RULE(int) yy_mkBlock(yycontext *yy); /* 12 */
YY_RULE(int) yy_LBRACE(yycontext *yy); /* 11 */
YY_RULE(int) yy_events(yycontext *yy); /* 10 */
YY_RULE(int) yy_params(yycontext *yy); /* 9 */
YY_RULE(int) yy_id(yycontext *yy); /* 8 */
YY_RULE(int) yy_STATE(yycontext *yy); /* 7 */
YY_RULE(int) yy_eol(yycontext *yy); /* 6 */
YY_RULE(int) yy_stmt(yycontext *yy); /* 5 */
YY_RULE(int) yy_define(yycontext *yy); /* 4 */
YY_RULE(int) yy_state(yycontext *yy); /* 3 */
YY_RULE(int) yy__(yycontext *yy); /* 2 */
YY_RULE(int) yy_start(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_newline(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_newline\n"));
  {
#line 162
   nlines++;;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_id(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_id\n"));
  {
#line 148
   __ = intern(yytext);  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_integer(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_integer\n"));
  {
#line 146
   __ = newInteger(atoi(yytext)) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_mkArray(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_mkArray\n"));
  {
#line 144
   __ = newArray(0) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_array(yycontext *yy, char *yytext, int yyleng)
{
#define e yy->__val[-1]
#define a yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_array\n"));
  {
#line 143
   __ = a ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef e
#undef a
}
YY_ACTION(void) yy_2_array(yycontext *yy, char *yytext, int yyleng)
{
#define e yy->__val[-1]
#define a yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_array\n"));
  {
#line 142
   Array_append(a, e) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef e
#undef a
}
YY_ACTION(void) yy_1_array(yycontext *yy, char *yytext, int yyleng)
{
#define e yy->__val[-1]
#define a yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_array\n"));
  {
#line 141
   Array_append(a, e) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef e
#undef a
}
YY_ACTION(void) yy_2_value(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_value\n"));
  {
#line 137
   __ = newGetVar(i,nlines) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef lhs
}
YY_ACTION(void) yy_1_value(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_value\n"));
  {
#line 135
   __ = lhs ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef lhs
}
YY_ACTION(void) yy_1_index(yycontext *yy, char *yytext, int yyleng)
{
#define e yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_index\n"));
  {
#line 133
   __ = e ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef e
}
YY_ACTION(void) yy_5_postfix(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define a yy->__val[-2]
#define v yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_postfix\n"));
  {
#line 131
   __ = v ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef a
#undef v
}
YY_ACTION(void) yy_4_postfix(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define a yy->__val[-2]
#define v yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_postfix\n"));
  {
#line 130
   v = newGetArray(v, i) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef a
#undef v
}
YY_ACTION(void) yy_3_postfix(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define a yy->__val[-2]
#define v yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_postfix\n"));
  {
#line 129
   v = newCall(a, v, nlines) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef a
#undef v
}
YY_ACTION(void) yy_2_postfix(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define a yy->__val[-2]
#define v yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_postfix\n"));
  {
#line 128
   __ = newUnyop(ADEC, v) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef a
#undef v
}
YY_ACTION(void) yy_1_postfix(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define a yy->__val[-2]
#define v yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_postfix\n"));
  {
#line 127
   __ = newUnyop(AINC, v) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef a
#undef v
}
YY_ACTION(void) yy_4_prefix(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_prefix\n"));
  {
#line 124
   __ = newUnyop(BDEC, x) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
}
YY_ACTION(void) yy_3_prefix(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_prefix\n"));
  {
#line 123
   __ = newUnyop(BINC, x) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
}
YY_ACTION(void) yy_2_prefix(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_prefix\n"));
  {
#line 122
   __ = newUnyop(NOT, x) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
}
YY_ACTION(void) yy_1_prefix(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_prefix\n"));
  {
#line 121
   __ = newUnyop(NEG, x) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
}
YY_ACTION(void) yy_4_mul(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_mul\n"));
  {
#line 118
   __ = lhs ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_3_mul(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_mul\n"));
  {
#line 117
   lhs = newBinop(MOD, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_2_mul(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_mul\n"));
  {
#line 116
   lhs = newBinop(DIV, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_1_mul(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_mul\n"));
  {
#line 115
   lhs = newBinop(MUL, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_3_add(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_add\n"));
  {
#line 113
   __ = lhs ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_2_add(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_add\n"));
  {
#line 112
   lhs = newBinop(SUB, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_1_add(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_add\n"));
  {
#line 111
   lhs = newBinop(ADD, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_5_ineq(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_ineq\n"));
  {
#line 109
   __ = lhs ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_4_ineq(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_ineq\n"));
  {
#line 108
   lhs = newBinop(LT, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_3_ineq(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_ineq\n"));
  {
#line 107
   lhs = newBinop(LE, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_2_ineq(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_ineq\n"));
  {
#line 106
   lhs = newBinop(GE, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_1_ineq(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_ineq\n"));
  {
#line 105
   lhs = newBinop(GT, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_3_eqop(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_eqop\n"));
  {
#line 103
   __ = lhs ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_2_eqop(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_eqop\n"));
  {
#line 102
   lhs = newBinop(NE, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_1_eqop(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_eqop\n"));
  {
#line 101
   lhs = newBinop(EQ, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_2_assignment(yycontext *yy, char *yytext, int yyleng)
{
#define v yy->__val[-1]
#define x yy->__val[-2]
#define i yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_assignment\n"));
  {
#line 98
   __ = newSetArray(v, i, x, SCOPE_LOCAL); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef v
#undef x
#undef i
}
YY_ACTION(void) yy_1_assignment(yycontext *yy, char *yytext, int yyleng)
{
#define v yy->__val[-1]
#define x yy->__val[-2]
#define i yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_assignment\n"));
  {
#line 97
   __ = newSetVar(i, x, SCOPE_LOCAL, nlines) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef v
#undef x
#undef i
}
YY_ACTION(void) yy_2_stt_local_assignment(yycontext *yy, char *yytext, int yyleng)
{
#define v yy->__val[-1]
#define x yy->__val[-2]
#define i yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_stt_local_assignment\n"));
  {
#line 95
   __ = newSetArray(v, i, x, SCOPE_STATE_LOCAL); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef v
#undef x
#undef i
}
YY_ACTION(void) yy_1_stt_local_assignment(yycontext *yy, char *yytext, int yyleng)
{
#define v yy->__val[-1]
#define x yy->__val[-2]
#define i yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_stt_local_assignment\n"));
  {
#line 94
   __ = newSetVar(i, x, SCOPE_STATE_LOCAL, nlines) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef v
#undef x
#undef i
}
YY_ACTION(void) yy_3_args(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define a yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_args\n"));
  {
#line 90
   __ = a ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef a
}
YY_ACTION(void) yy_2_args(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define a yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_args\n"));
  {
#line 87
   a = newPair(i, a) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef a
}
YY_ACTION(void) yy_1_args(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define a yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_args\n"));
  {
#line 86
   a = newPair(i, a) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef a
}
YY_ACTION(void) yy_10_stmt(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define k yy->__val[-2]
#define i yy->__val[-3]
#define t yy->__val[-4]
#define s yy->__val[-5]
#define c yy->__val[-6]
#define a yy->__val[-7]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_10_stmt\n"));
  {
#line 83
   fatal("line %d ERROR: syntax error ';'\n",nlines);;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
#undef k
#undef i
#undef t
#undef s
#undef c
#undef a
}
YY_ACTION(void) yy_9_stmt(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define k yy->__val[-2]
#define i yy->__val[-3]
#define t yy->__val[-4]
#define s yy->__val[-5]
#define c yy->__val[-6]
#define a yy->__val[-7]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_9_stmt\n"));
  {
#line 82
   result = false; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
#undef k
#undef i
#undef t
#undef s
#undef c
#undef a
}
YY_ACTION(void) yy_8_stmt(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define k yy->__val[-2]
#define i yy->__val[-3]
#define t yy->__val[-4]
#define s yy->__val[-5]
#define c yy->__val[-6]
#define a yy->__val[-7]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_8_stmt\n"));
  {
#line 81
   result = x; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
#undef k
#undef i
#undef t
#undef s
#undef c
#undef a
}
YY_ACTION(void) yy_7_stmt(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define k yy->__val[-2]
#define i yy->__val[-3]
#define t yy->__val[-4]
#define s yy->__val[-5]
#define c yy->__val[-6]
#define a yy->__val[-7]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_7_stmt\n"));
  {
#line 80
   __ = newTransition(i); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
#undef k
#undef i
#undef t
#undef s
#undef c
#undef a
}
YY_ACTION(void) yy_6_stmt(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define k yy->__val[-2]
#define i yy->__val[-3]
#define t yy->__val[-4]
#define s yy->__val[-5]
#define c yy->__val[-6]
#define a yy->__val[-7]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_stmt\n"));
  {
#line 79
   __ = newReturn(x); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
#undef k
#undef i
#undef t
#undef s
#undef c
#undef a
}
YY_ACTION(void) yy_5_stmt(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define k yy->__val[-2]
#define i yy->__val[-3]
#define t yy->__val[-4]
#define s yy->__val[-5]
#define c yy->__val[-6]
#define a yy->__val[-7]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_stmt\n"));
  {
#line 78
   __ = newLoop(i, c, t, s) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
#undef k
#undef i
#undef t
#undef s
#undef c
#undef a
}
YY_ACTION(void) yy_4_stmt(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define k yy->__val[-2]
#define i yy->__val[-3]
#define t yy->__val[-4]
#define s yy->__val[-5]
#define c yy->__val[-6]
#define a yy->__val[-7]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_stmt\n"));
  {
#line 74
   __ = newLoop(false, c,false, s) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
#undef k
#undef i
#undef t
#undef s
#undef c
#undef a
}
YY_ACTION(void) yy_3_stmt(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define k yy->__val[-2]
#define i yy->__val[-3]
#define t yy->__val[-4]
#define s yy->__val[-5]
#define c yy->__val[-6]
#define a yy->__val[-7]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_stmt\n"));
  {
#line 73
   __ = newIf(c, s, false) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
#undef k
#undef i
#undef t
#undef s
#undef c
#undef a
}
YY_ACTION(void) yy_2_stmt(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define k yy->__val[-2]
#define i yy->__val[-3]
#define t yy->__val[-4]
#define s yy->__val[-5]
#define c yy->__val[-6]
#define a yy->__val[-7]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_stmt\n"));
  {
#line 72
   __ = newIf(c, s, t) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
#undef k
#undef i
#undef t
#undef s
#undef c
#undef a
}
YY_ACTION(void) yy_1_stmt(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define k yy->__val[-2]
#define i yy->__val[-3]
#define t yy->__val[-4]
#define s yy->__val[-5]
#define c yy->__val[-6]
#define a yy->__val[-7]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_stmt\n"));
  {
#line 70
   __ = newPrint(a) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
#undef k
#undef i
#undef t
#undef s
#undef c
#undef a
}
YY_ACTION(void) yy_3_define(yycontext *yy, char *yytext, int yyleng)
{
#define v yy->__val[-1]
#define x yy->__val[-2]
#define b yy->__val[-3]
#define p yy->__val[-4]
#define i yy->__val[-5]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_define\n"));
  {
#line 68
   __ = newSetArray(v, i, x, SCOPE_GLOBAL); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef v
#undef x
#undef b
#undef p
#undef i
}
YY_ACTION(void) yy_2_define(yycontext *yy, char *yytext, int yyleng)
{
#define v yy->__val[-1]
#define x yy->__val[-2]
#define b yy->__val[-3]
#define p yy->__val[-4]
#define i yy->__val[-5]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_define\n"));
  {
#line 67
   __ = newSetVar(i, x, SCOPE_GLOBAL, nlines) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef v
#undef x
#undef b
#undef p
#undef i
}
YY_ACTION(void) yy_1_define(yycontext *yy, char *yytext, int yyleng)
{
#define v yy->__val[-1]
#define x yy->__val[-2]
#define b yy->__val[-3]
#define p yy->__val[-4]
#define i yy->__val[-5]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_define\n"));
  {
#line 66
   __ = newSetVar(i, newUserFunc(p, b),0, nlines); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef v
#undef x
#undef b
#undef p
#undef i
}
YY_ACTION(void) yy_1_mkBlock(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_mkBlock\n"));
  {
#line 64
   __ = newBlock() ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_block(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define b yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_block\n"));
  {
#line 62
   __ = b ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
#undef b
}
YY_ACTION(void) yy_1_block(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define b yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_block\n"));
  {
#line 60
   Block_append(b, s) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
#undef b
}
YY_ACTION(void) yy_1_mkFalse(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_mkFalse\n"));
  {
#line 55
   __ = false ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_mkNil(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_mkNil\n"));
  {
#line 54
   __ = nil ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_params(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define p yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_params\n"));
  {
#line 52
   __ = p ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef p
}
YY_ACTION(void) yy_2_params(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define p yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_params\n"));
  {
#line 49
   p = newPair(i, p) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef p
}
YY_ACTION(void) yy_1_params(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define p yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_params\n"));
  {
#line 48
   p = newPair(i, p) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef p
}
YY_ACTION(void) yy_3_eparams(yycontext *yy, char *yytext, int yyleng)
{
#define c yy->__val[-1]
#define i yy->__val[-2]
#define p yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_eparams\n"));
  {
#line 45
   __ = p ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef c
#undef i
#undef p
}
YY_ACTION(void) yy_2_eparams(yycontext *yy, char *yytext, int yyleng)
{
#define c yy->__val[-1]
#define i yy->__val[-2]
#define p yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_eparams\n"));
  {
#line 42
   p = newPair(newPair(i,c), p) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef c
#undef i
#undef p
}
YY_ACTION(void) yy_1_eparams(yycontext *yy, char *yytext, int yyleng)
{
#define c yy->__val[-1]
#define i yy->__val[-2]
#define p yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_eparams\n"));
  {
#line 41
   p = newPair(newPair(i,c), p) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef c
#undef i
#undef p
}
YY_ACTION(void) yy_1_event(yycontext *yy, char *yytext, int yyleng)
{
#define b yy->__val[-1]
#define p yy->__val[-2]
#define i yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_event\n"));
  {
#line 38
   __ = newEvent(i, p, b, nlines); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef b
#undef p
#undef i
}
YY_ACTION(void) yy_2_events(yycontext *yy, char *yytext, int yyleng)
{
#define e yy->__val[-1]
#define b yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_events\n"));
  {
#line 36
   __ = b ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef e
#undef b
}
YY_ACTION(void) yy_1_events(yycontext *yy, char *yytext, int yyleng)
{
#define e yy->__val[-1]
#define b yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_events\n"));
  {
#line 34
   Event_Block_append(b, e) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef e
#undef b
}
YY_ACTION(void) yy_1_state(yycontext *yy, char *yytext, int yyleng)
{
#define e yy->__val[-1]
#define p yy->__val[-2]
#define i yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_state\n"));
  {
#line 29
   __ = newState(i, p, e,nlines); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef e
#undef p
#undef i
}
YY_ACTION(void) yy_5_start(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_start\n"));
  {
#line 27
   fatal("line %d: syntax error: %s", nlines, yytext); result = parserRetFlags[PARSER_ERROR]; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_4_start(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_start\n"));
  {
#line 26
   printf("\n%d objects allocated\n", nobj); result = parserRetFlags[PARSER_FINISH]; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_3_start(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_start\n"));
  {
#line 25
   result = s; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_2_start(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_start\n"));
  {
#line 24
   result = s; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_1_start(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_start\n"));
  {
#line 23
  result = s;;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}

YY_RULE(int) yy_newline(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "newline"));  if (!yymatchClass(yy, (unsigned char *)"\000\044\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;  yyDo(yy, yy_1_newline, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "newline", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "newline", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_blank(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "blank"));
  {  int yypos3= yy->__pos, yythunkpos3= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l4;  goto l3;
  l4:;	  yy->__pos= yypos3; yy->__thunkpos= yythunkpos3;  if (!yy_newline(yy)) goto l5;  goto l3;
  l5:;	  yy->__pos= yypos3; yy->__thunkpos= yythunkpos3;  if (!yymatchString(yy, "//")) goto l2;
  l6:;	
  {  int yypos7= yy->__pos, yythunkpos7= yy->__thunkpos;
  {  int yypos8= yy->__pos, yythunkpos8= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\044\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l8;  goto l7;
  l8:;	  yy->__pos= yypos8; yy->__thunkpos= yythunkpos8;
  }  if (!yymatchDot(yy)) goto l7;  goto l6;
  l7:;	  yy->__pos= yypos7; yy->__thunkpos= yythunkpos7;
  }
  }
  l3:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "blank", yy->__buf+yy->__pos));
  return 1;
  l2:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "blank", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_alnum(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "alnum"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l9;
  yyprintf((stderr, "  ok   %s @ %s\n", "alnum", yy->__buf+yy->__pos));
  return 1;
  l9:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "alnum", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_alpha(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "alpha"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l10;
  yyprintf((stderr, "  ok   %s @ %s\n", "alpha", yy->__buf+yy->__pos));
  return 1;
  l10:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "alpha", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_mkArray(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "mkArray"));  yyDo(yy, yy_1_mkArray, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "mkArray", yy->__buf+yy->__pos));
  return 1;
  l11:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "mkArray", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_array(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "array"));  if (!yy_LBRACE(yy)) goto l12;  if (!yy_mkArray(yy)) goto l12;  yyDo(yy, yySet, -2, 0);
  {  int yypos13= yy->__pos, yythunkpos13= yy->__thunkpos;  if (!yy_expr(yy)) goto l13;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_array, yy->__begin, yy->__end);
  l15:;	
  {  int yypos16= yy->__pos, yythunkpos16= yy->__thunkpos;  if (!yy_COMMA(yy)) goto l16;  if (!yy_expr(yy)) goto l16;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_array, yy->__begin, yy->__end);  goto l15;
  l16:;	  yy->__pos= yypos16; yy->__thunkpos= yythunkpos16;
  }  goto l14;
  l13:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;
  }
  l14:;	  if (!yy_RBRACE(yy)) goto l12;  yyDo(yy, yy_3_array, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "array", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l12:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "array", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_integer(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "integer"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l17;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l17;
  l18:;	
  {  int yypos19= yy->__pos, yythunkpos19= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l19;  goto l18;
  l19:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l17;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l17;  yyDo(yy, yy_1_integer, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "integer", yy->__buf+yy->__pos));
  return 1;
  l17:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "integer", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RBRAK(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RBRAK"));  if (!yymatchChar(yy, ']')) goto l20;  if (!yy__(yy)) goto l20;
  yyprintf((stderr, "  ok   %s @ %s\n", "RBRAK", yy->__buf+yy->__pos));
  return 1;
  l20:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RBRAK", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LBRAK(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LBRAK"));  if (!yymatchChar(yy, '[')) goto l21;  if (!yy__(yy)) goto l21;
  yyprintf((stderr, "  ok   %s @ %s\n", "LBRAK", yy->__buf+yy->__pos));
  return 1;
  l21:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LBRAK", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_MMINUS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "MMINUS"));  if (!yymatchString(yy, "--")) goto l22;
  {  int yypos23= yy->__pos, yythunkpos23= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l23;  goto l22;
  l23:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "MMINUS", yy->__buf+yy->__pos));
  return 1;
  l22:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MMINUS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PPLUS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PPLUS"));  if (!yymatchString(yy, "++")) goto l24;
  {  int yypos25= yy->__pos, yythunkpos25= yy->__thunkpos;  if (!yymatchChar(yy, '+')) goto l25;  goto l24;
  l25:;	  yy->__pos= yypos25; yy->__thunkpos= yythunkpos25;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "PPLUS", yy->__buf+yy->__pos));
  return 1;
  l24:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PPLUS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PLING(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PLING"));  if (!yymatchChar(yy, '!')) goto l26;
  {  int yypos27= yy->__pos, yythunkpos27= yy->__thunkpos;  if (!yymatchChar(yy, '=')) goto l27;  goto l26;
  l27:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;
  }  if (!yy__(yy)) goto l26;
  yyprintf((stderr, "  ok   %s @ %s\n", "PLING", yy->__buf+yy->__pos));
  return 1;
  l26:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PLING", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_postfix(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "postfix"));
  {  int yypos29= yy->__pos, yythunkpos29= yy->__thunkpos;  if (!yy_value(yy)) goto l30;  yyDo(yy, yySet, -3, 0);  if (!yy_PPLUS(yy)) goto l30;  yyDo(yy, yy_1_postfix, yy->__begin, yy->__end);  goto l29;
  l30:;	  yy->__pos= yypos29; yy->__thunkpos= yythunkpos29;  if (!yy_value(yy)) goto l31;  yyDo(yy, yySet, -3, 0);  if (!yy_MMINUS(yy)) goto l31;  yyDo(yy, yy_2_postfix, yy->__begin, yy->__end);  goto l29;
  l31:;	  yy->__pos= yypos29; yy->__thunkpos= yythunkpos29;  if (!yy_value(yy)) goto l28;  yyDo(yy, yySet, -3, 0);
  l32:;	
  {  int yypos33= yy->__pos, yythunkpos33= yy->__thunkpos;
  {  int yypos34= yy->__pos, yythunkpos34= yy->__thunkpos;  if (!yy_args(yy)) goto l35;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_3_postfix, yy->__begin, yy->__end);  goto l34;
  l35:;	  yy->__pos= yypos34; yy->__thunkpos= yythunkpos34;  if (!yy_index(yy)) goto l33;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_4_postfix, yy->__begin, yy->__end);
  }
  l34:;	  goto l32;
  l33:;	  yy->__pos= yypos33; yy->__thunkpos= yythunkpos33;
  }  yyDo(yy, yy_5_postfix, yy->__begin, yy->__end);
  }
  l29:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "postfix", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l28:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "postfix", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PCENT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PCENT"));  if (!yymatchChar(yy, '%')) goto l36;  if (!yy__(yy)) goto l36;
  yyprintf((stderr, "  ok   %s @ %s\n", "PCENT", yy->__buf+yy->__pos));
  return 1;
  l36:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PCENT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SLASH(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SLASH"));  if (!yymatchChar(yy, '/')) goto l37;  if (!yy__(yy)) goto l37;
  yyprintf((stderr, "  ok   %s @ %s\n", "SLASH", yy->__buf+yy->__pos));
  return 1;
  l37:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SLASH", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_STAR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "STAR"));  if (!yymatchChar(yy, '*')) goto l38;  if (!yy__(yy)) goto l38;
  yyprintf((stderr, "  ok   %s @ %s\n", "STAR", yy->__buf+yy->__pos));
  return 1;
  l38:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STAR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_prefix(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "prefix"));
  {  int yypos40= yy->__pos, yythunkpos40= yy->__thunkpos;  if (!yy_MINUS(yy)) goto l41;  if (!yy_postfix(yy)) goto l41;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_prefix, yy->__begin, yy->__end);  goto l40;
  l41:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;  if (!yy_PLING(yy)) goto l42;  if (!yy_postfix(yy)) goto l42;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_prefix, yy->__begin, yy->__end);  goto l40;
  l42:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;  if (!yy_PPLUS(yy)) goto l43;  if (!yy_postfix(yy)) goto l43;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_3_prefix, yy->__begin, yy->__end);  goto l40;
  l43:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;  if (!yy_MMINUS(yy)) goto l44;  if (!yy_postfix(yy)) goto l44;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_4_prefix, yy->__begin, yy->__end);  goto l40;
  l44:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;  if (!yy_postfix(yy)) goto l39;
  }
  l40:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "prefix", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l39:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "prefix", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_MINUS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "MINUS"));  if (!yymatchChar(yy, '-')) goto l45;
  {  int yypos46= yy->__pos, yythunkpos46= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l46;  goto l45;
  l46:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;
  }  if (!yy__(yy)) goto l45;
  yyprintf((stderr, "  ok   %s @ %s\n", "MINUS", yy->__buf+yy->__pos));
  return 1;
  l45:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MINUS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PLUS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PLUS"));  if (!yymatchChar(yy, '+')) goto l47;
  {  int yypos48= yy->__pos, yythunkpos48= yy->__thunkpos;  if (!yymatchChar(yy, '+')) goto l48;  goto l47;
  l48:;	  yy->__pos= yypos48; yy->__thunkpos= yythunkpos48;
  }  if (!yy__(yy)) goto l47;
  yyprintf((stderr, "  ok   %s @ %s\n", "PLUS", yy->__buf+yy->__pos));
  return 1;
  l47:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PLUS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_mul(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "mul"));  if (!yy_prefix(yy)) goto l49;  yyDo(yy, yySet, -2, 0);
  l50:;	
  {  int yypos51= yy->__pos, yythunkpos51= yy->__thunkpos;
  {  int yypos52= yy->__pos, yythunkpos52= yy->__thunkpos;  if (!yy_STAR(yy)) goto l53;  if (!yy_prefix(yy)) goto l53;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_mul, yy->__begin, yy->__end);  goto l52;
  l53:;	  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;  if (!yy_SLASH(yy)) goto l54;  if (!yy_prefix(yy)) goto l54;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_mul, yy->__begin, yy->__end);  goto l52;
  l54:;	  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;  if (!yy_PCENT(yy)) goto l51;  if (!yy_prefix(yy)) goto l51;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_3_mul, yy->__begin, yy->__end);
  }
  l52:;	  goto l50;
  l51:;	  yy->__pos= yypos51; yy->__thunkpos= yythunkpos51;
  }  yyDo(yy, yy_4_mul, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "mul", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l49:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "mul", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LESS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LESS"));  if (!yymatchChar(yy, '<')) goto l55;
  {  int yypos56= yy->__pos, yythunkpos56= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\060\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l56;  goto l55;
  l56:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;
  }  if (!yy__(yy)) goto l55;
  yyprintf((stderr, "  ok   %s @ %s\n", "LESS", yy->__buf+yy->__pos));
  return 1;
  l55:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LESS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LESSEQ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LESSEQ"));  if (!yymatchString(yy, "<=")) goto l57;  if (!yy__(yy)) goto l57;
  yyprintf((stderr, "  ok   %s @ %s\n", "LESSEQ", yy->__buf+yy->__pos));
  return 1;
  l57:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LESSEQ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_GREATEQ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "GREATEQ"));  if (!yymatchString(yy, ">=")) goto l58;  if (!yy__(yy)) goto l58;
  yyprintf((stderr, "  ok   %s @ %s\n", "GREATEQ", yy->__buf+yy->__pos));
  return 1;
  l58:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "GREATEQ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_GREATER(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "GREATER"));  if (!yymatchChar(yy, '>')) goto l59;
  {  int yypos60= yy->__pos, yythunkpos60= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\140\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l60;  goto l59;
  l60:;	  yy->__pos= yypos60; yy->__thunkpos= yythunkpos60;
  }  if (!yy__(yy)) goto l59;
  yyprintf((stderr, "  ok   %s @ %s\n", "GREATER", yy->__buf+yy->__pos));
  return 1;
  l59:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "GREATER", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_add(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "add"));  if (!yy_mul(yy)) goto l61;  yyDo(yy, yySet, -2, 0);
  l62:;	
  {  int yypos63= yy->__pos, yythunkpos63= yy->__thunkpos;
  {  int yypos64= yy->__pos, yythunkpos64= yy->__thunkpos;  if (!yy_PLUS(yy)) goto l65;  if (!yy_mul(yy)) goto l65;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_add, yy->__begin, yy->__end);  goto l64;
  l65:;	  yy->__pos= yypos64; yy->__thunkpos= yythunkpos64;  if (!yy_MINUS(yy)) goto l63;  if (!yy_mul(yy)) goto l63;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_add, yy->__begin, yy->__end);
  }
  l64:;	  goto l62;
  l63:;	  yy->__pos= yypos63; yy->__thunkpos= yythunkpos63;
  }  yyDo(yy, yy_3_add, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "add", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l61:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "add", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NOTEQ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NOTEQ"));  if (!yymatchString(yy, "!=")) goto l66;  if (!yy__(yy)) goto l66;
  yyprintf((stderr, "  ok   %s @ %s\n", "NOTEQ", yy->__buf+yy->__pos));
  return 1;
  l66:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NOTEQ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EQUAL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EQUAL"));  if (!yymatchString(yy, "==")) goto l67;  if (!yy__(yy)) goto l67;
  yyprintf((stderr, "  ok   %s @ %s\n", "EQUAL", yy->__buf+yy->__pos));
  return 1;
  l67:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EQUAL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ineq(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "ineq"));  if (!yy_add(yy)) goto l68;  yyDo(yy, yySet, -2, 0);
  l69:;	
  {  int yypos70= yy->__pos, yythunkpos70= yy->__thunkpos;
  {  int yypos71= yy->__pos, yythunkpos71= yy->__thunkpos;  if (!yy_GREATER(yy)) goto l72;  if (!yy_add(yy)) goto l72;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_ineq, yy->__begin, yy->__end);  goto l71;
  l72:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;  if (!yy_GREATEQ(yy)) goto l73;  if (!yy_add(yy)) goto l73;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_ineq, yy->__begin, yy->__end);  goto l71;
  l73:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;  if (!yy_LESSEQ(yy)) goto l74;  if (!yy_add(yy)) goto l74;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_3_ineq, yy->__begin, yy->__end);  goto l71;
  l74:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;  if (!yy_LESS(yy)) goto l70;  if (!yy_add(yy)) goto l70;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_4_ineq, yy->__begin, yy->__end);
  }
  l71:;	  goto l69;
  l70:;	  yy->__pos= yypos70; yy->__thunkpos= yythunkpos70;
  }  yyDo(yy, yy_5_ineq, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "ineq", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l68:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ineq", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RET(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RET"));  if (!yymatchString(yy, "return")) goto l75;  if (!yy__(yy)) goto l75;
  yyprintf((stderr, "  ok   %s @ %s\n", "RET", yy->__buf+yy->__pos));
  return 1;
  l75:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RET", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_FOR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "FOR"));  if (!yymatchString(yy, "for")) goto l76;  if (!yy__(yy)) goto l76;
  yyprintf((stderr, "  ok   %s @ %s\n", "FOR", yy->__buf+yy->__pos));
  return 1;
  l76:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FOR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_WHILE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "WHILE"));  if (!yymatchString(yy, "while")) goto l77;  if (!yy__(yy)) goto l77;
  yyprintf((stderr, "  ok   %s @ %s\n", "WHILE", yy->__buf+yy->__pos));
  return 1;
  l77:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "WHILE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ELSE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ELSE"));  if (!yymatchString(yy, "else")) goto l78;  if (!yy__(yy)) goto l78;
  yyprintf((stderr, "  ok   %s @ %s\n", "ELSE", yy->__buf+yy->__pos));
  return 1;
  l78:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ELSE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_expr(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "expr"));  if (!yy_assignment(yy)) goto l79;
  yyprintf((stderr, "  ok   %s @ %s\n", "expr", yy->__buf+yy->__pos));
  return 1;
  l79:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expr", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IF(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IF"));  if (!yymatchString(yy, "if")) goto l80;  if (!yy__(yy)) goto l80;
  yyprintf((stderr, "  ok   %s @ %s\n", "IF", yy->__buf+yy->__pos));
  return 1;
  l80:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IF", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SEMI(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SEMI"));  if (!yymatchChar(yy, ';')) goto l81;  if (!yy__(yy)) goto l81;
  yyprintf((stderr, "  ok   %s @ %s\n", "SEMI", yy->__buf+yy->__pos));
  return 1;
  l81:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SEMI", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_args(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "args"));  if (!yy_LPAR(yy)) goto l82;  if (!yy_mkNil(yy)) goto l82;  yyDo(yy, yySet, -2, 0);
  {  int yypos83= yy->__pos, yythunkpos83= yy->__thunkpos;  if (!yy_expr(yy)) goto l83;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_args, yy->__begin, yy->__end);
  l85:;	
  {  int yypos86= yy->__pos, yythunkpos86= yy->__thunkpos;  if (!yy_COMMA(yy)) goto l86;  if (!yy_expr(yy)) goto l86;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_args, yy->__begin, yy->__end);  goto l85;
  l86:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  }  goto l84;
  l83:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;
  }
  l84:;	  if (!yy_RPAR(yy)) goto l82;  yyDo(yy, yy_3_args, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "args", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l82:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "args", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PRINT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PRINT"));  if (!yymatchString(yy, "print")) goto l87;  if (!yy__(yy)) goto l87;
  yyprintf((stderr, "  ok   %s @ %s\n", "PRINT", yy->__buf+yy->__pos));
  return 1;
  l87:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PRINT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_index(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "index"));  if (!yy_LBRAK(yy)) goto l88;  if (!yy_expr(yy)) goto l88;  yyDo(yy, yySet, -1, 0);  if (!yy_RBRAK(yy)) goto l88;  yyDo(yy, yy_1_index, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "index", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l88:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "index", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_value(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "value"));
  {  int yypos90= yy->__pos, yythunkpos90= yy->__thunkpos;  if (!yy_LPAR(yy)) goto l91;  if (!yy_expr(yy)) goto l91;  yyDo(yy, yySet, -2, 0);  if (!yy_RPAR(yy)) goto l91;  yyDo(yy, yy_1_value, yy->__begin, yy->__end);  goto l90;
  l91:;	  yy->__pos= yypos90; yy->__thunkpos= yythunkpos90;  if (!yy_integer(yy)) goto l92;  goto l90;
  l92:;	  yy->__pos= yypos90; yy->__thunkpos= yythunkpos90;  if (!yy_id(yy)) goto l93;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_value, yy->__begin, yy->__end);  goto l90;
  l93:;	  yy->__pos= yypos90; yy->__thunkpos= yythunkpos90;  if (!yy_array(yy)) goto l89;
  }
  l90:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "value", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l89:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "value", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_assignment(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "assignment"));
  {  int yypos95= yy->__pos, yythunkpos95= yy->__thunkpos;  if (!yy_id(yy)) goto l96;  yyDo(yy, yySet, -3, 0);  if (!yy_ASSIGN(yy)) goto l96;  if (!yy_assignment(yy)) goto l96;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_1_assignment, yy->__begin, yy->__end);  goto l95;
  l96:;	  yy->__pos= yypos95; yy->__thunkpos= yythunkpos95;  if (!yy_value(yy)) goto l97;  yyDo(yy, yySet, -1, 0);  if (!yy_index(yy)) goto l97;  yyDo(yy, yySet, -3, 0);  if (!yy_ASSIGN(yy)) goto l97;  if (!yy_assignment(yy)) goto l97;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_2_assignment, yy->__begin, yy->__end);  goto l95;
  l97:;	  yy->__pos= yypos95; yy->__thunkpos= yythunkpos95;  if (!yy_eqop(yy)) goto l94;
  }
  l95:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "assignment", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l94:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "assignment", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ASSIGN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ASSIGN"));  if (!yymatchChar(yy, '=')) goto l98;
  {  int yypos99= yy->__pos, yythunkpos99= yy->__thunkpos;  if (!yymatchChar(yy, '=')) goto l99;  goto l98;
  l99:;	  yy->__pos= yypos99; yy->__thunkpos= yythunkpos99;
  }  if (!yy__(yy)) goto l98;
  yyprintf((stderr, "  ok   %s @ %s\n", "ASSIGN", yy->__buf+yy->__pos));
  return 1;
  l98:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ASSIGN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_FUNC(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "FUNC"));  if (!yymatchString(yy, "fn")) goto l100;  if (!yy__(yy)) goto l100;
  yyprintf((stderr, "  ok   %s @ %s\n", "FUNC", yy->__buf+yy->__pos));
  return 1;
  l100:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FUNC", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RPAR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RPAR"));  if (!yymatchChar(yy, ')')) goto l101;  if (!yy__(yy)) goto l101;
  yyprintf((stderr, "  ok   %s @ %s\n", "RPAR", yy->__buf+yy->__pos));
  return 1;
  l101:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RPAR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_COMMA(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "COMMA"));  if (!yymatchChar(yy, ',')) goto l102;  if (!yy__(yy)) goto l102;
  yyprintf((stderr, "  ok   %s @ %s\n", "COMMA", yy->__buf+yy->__pos));
  return 1;
  l102:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COMMA", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_eqop(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "eqop"));  if (!yy_ineq(yy)) goto l103;  yyDo(yy, yySet, -2, 0);
  l104:;	
  {  int yypos105= yy->__pos, yythunkpos105= yy->__thunkpos;
  {  int yypos106= yy->__pos, yythunkpos106= yy->__thunkpos;  if (!yy_EQUAL(yy)) goto l107;  if (!yy_ineq(yy)) goto l107;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_eqop, yy->__begin, yy->__end);  goto l106;
  l107:;	  yy->__pos= yypos106; yy->__thunkpos= yythunkpos106;  if (!yy_NOTEQ(yy)) goto l105;  if (!yy_ineq(yy)) goto l105;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_eqop, yy->__begin, yy->__end);
  }
  l106:;	  goto l104;
  l105:;	  yy->__pos= yypos105; yy->__thunkpos= yythunkpos105;
  }  yyDo(yy, yy_3_eqop, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "eqop", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l103:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eqop", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_mkFalse(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "mkFalse"));  yyDo(yy, yy_1_mkFalse, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "mkFalse", yy->__buf+yy->__pos));
  return 1;
  l108:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "mkFalse", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_mkNil(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "mkNil"));  yyDo(yy, yy_1_mkNil, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "mkNil", yy->__buf+yy->__pos));
  return 1;
  l109:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "mkNil", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LPAR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LPAR"));  if (!yymatchChar(yy, '(')) goto l110;  if (!yy__(yy)) goto l110;
  yyprintf((stderr, "  ok   %s @ %s\n", "LPAR", yy->__buf+yy->__pos));
  return 1;
  l110:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LPAR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_block(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "block"));  if (!yy_LBRACE(yy)) goto l111;  if (!yy_mkBlock(yy)) goto l111;  yyDo(yy, yySet, -2, 0);
  {  int yypos114= yy->__pos, yythunkpos114= yy->__thunkpos;  if (!yy_RBRACE(yy)) goto l114;  goto l111;
  l114:;	  yy->__pos= yypos114; yy->__thunkpos= yythunkpos114;
  }  if (!yy_stmt(yy)) goto l111;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_block, yy->__begin, yy->__end);
  l112:;	
  {  int yypos113= yy->__pos, yythunkpos113= yy->__thunkpos;
  {  int yypos115= yy->__pos, yythunkpos115= yy->__thunkpos;  if (!yy_RBRACE(yy)) goto l115;  goto l113;
  l115:;	  yy->__pos= yypos115; yy->__thunkpos= yythunkpos115;
  }  if (!yy_stmt(yy)) goto l113;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_block, yy->__begin, yy->__end);  goto l112;
  l113:;	  yy->__pos= yypos113; yy->__thunkpos= yythunkpos113;
  }  if (!yy_RBRACE(yy)) goto l111;  yyDo(yy, yy_2_block, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "block", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l111:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "block", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_eparams(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "eparams"));  if (!yy_LPAR(yy)) goto l116;  if (!yy_mkNil(yy)) goto l116;  yyDo(yy, yySet, -3, 0);
  {  int yypos117= yy->__pos, yythunkpos117= yy->__thunkpos;  if (!yy_id(yy)) goto l117;  yyDo(yy, yySet, -2, 0);  if (!yy_mkFalse(yy)) goto l117;  yyDo(yy, yySet, -1, 0);
  {  int yypos119= yy->__pos, yythunkpos119= yy->__thunkpos;  if (!yy_eqop(yy)) goto l119;  yyDo(yy, yySet, -1, 0);  goto l120;
  l119:;	  yy->__pos= yypos119; yy->__thunkpos= yythunkpos119;
  }
  l120:;	  yyDo(yy, yy_1_eparams, yy->__begin, yy->__end);
  l121:;	
  {  int yypos122= yy->__pos, yythunkpos122= yy->__thunkpos;  if (!yy_COMMA(yy)) goto l122;  if (!yy_id(yy)) goto l122;  yyDo(yy, yySet, -2, 0);  if (!yy_mkFalse(yy)) goto l122;  yyDo(yy, yySet, -1, 0);
  {  int yypos123= yy->__pos, yythunkpos123= yy->__thunkpos;  if (!yy_eqop(yy)) goto l123;  yyDo(yy, yySet, -1, 0);  goto l124;
  l123:;	  yy->__pos= yypos123; yy->__thunkpos= yythunkpos123;
  }
  l124:;	  yyDo(yy, yy_2_eparams, yy->__begin, yy->__end);  goto l121;
  l122:;	  yy->__pos= yypos122; yy->__thunkpos= yythunkpos122;
  }  goto l118;
  l117:;	  yy->__pos= yypos117; yy->__thunkpos= yythunkpos117;
  }
  l118:;	  if (!yy_RPAR(yy)) goto l116;  yyDo(yy, yy_3_eparams, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "eparams", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l116:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eparams", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_stt_local_assignment(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "stt_local_assignment"));
  {  int yypos126= yy->__pos, yythunkpos126= yy->__thunkpos;  if (!yy_id(yy)) goto l127;  yyDo(yy, yySet, -3, 0);  if (!yy_ASSIGN(yy)) goto l127;  if (!yy_assignment(yy)) goto l127;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_1_stt_local_assignment, yy->__begin, yy->__end);  goto l126;
  l127:;	  yy->__pos= yypos126; yy->__thunkpos= yythunkpos126;  if (!yy_value(yy)) goto l125;  yyDo(yy, yySet, -1, 0);  if (!yy_index(yy)) goto l125;  yyDo(yy, yySet, -3, 0);  if (!yy_ASSIGN(yy)) goto l125;  if (!yy_assignment(yy)) goto l125;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_2_stt_local_assignment, yy->__begin, yy->__end);
  }
  l126:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "stt_local_assignment", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l125:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "stt_local_assignment", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_event(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "event"));  if (!yy_id(yy)) goto l128;  yyDo(yy, yySet, -3, 0);  if (!yy_eparams(yy)) goto l128;  yyDo(yy, yySet, -2, 0);  if (!yy_block(yy)) goto l128;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_event, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "event", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l128:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "event", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RBRACE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RBRACE"));  if (!yymatchChar(yy, '}')) goto l129;  if (!yy__(yy)) goto l129;
  yyprintf((stderr, "  ok   %s @ %s\n", "RBRACE", yy->__buf+yy->__pos));
  return 1;
  l129:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RBRACE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_mkBlock(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "mkBlock"));  yyDo(yy, yy_1_mkBlock, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "mkBlock", yy->__buf+yy->__pos));
  return 1;
  l130:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "mkBlock", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LBRACE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LBRACE"));  if (!yymatchChar(yy, '{')) goto l131;  if (!yy__(yy)) goto l131;
  yyprintf((stderr, "  ok   %s @ %s\n", "LBRACE", yy->__buf+yy->__pos));
  return 1;
  l131:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LBRACE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_events(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "events"));  if (!yy_LBRACE(yy)) goto l132;  if (!yy_mkBlock(yy)) goto l132;  yyDo(yy, yySet, -2, 0);
  {  int yypos135= yy->__pos, yythunkpos135= yy->__thunkpos;  if (!yy_RBRACE(yy)) goto l135;  goto l132;
  l135:;	  yy->__pos= yypos135; yy->__thunkpos= yythunkpos135;
  }
  {  int yypos136= yy->__pos, yythunkpos136= yy->__thunkpos;  if (!yy_event(yy)) goto l137;  yyDo(yy, yySet, -1, 0);  goto l136;
  l137:;	  yy->__pos= yypos136; yy->__thunkpos= yythunkpos136;  if (!yy_stt_local_assignment(yy)) goto l132;  yyDo(yy, yySet, -1, 0);
  }
  l136:;	  yyDo(yy, yy_1_events, yy->__begin, yy->__end);
  l133:;	
  {  int yypos134= yy->__pos, yythunkpos134= yy->__thunkpos;
  {  int yypos138= yy->__pos, yythunkpos138= yy->__thunkpos;  if (!yy_RBRACE(yy)) goto l138;  goto l134;
  l138:;	  yy->__pos= yypos138; yy->__thunkpos= yythunkpos138;
  }
  {  int yypos139= yy->__pos, yythunkpos139= yy->__thunkpos;  if (!yy_event(yy)) goto l140;  yyDo(yy, yySet, -1, 0);  goto l139;
  l140:;	  yy->__pos= yypos139; yy->__thunkpos= yythunkpos139;  if (!yy_stt_local_assignment(yy)) goto l134;  yyDo(yy, yySet, -1, 0);
  }
  l139:;	  yyDo(yy, yy_1_events, yy->__begin, yy->__end);  goto l133;
  l134:;	  yy->__pos= yypos134; yy->__thunkpos= yythunkpos134;
  }  if (!yy_RBRACE(yy)) goto l132;  yyDo(yy, yy_2_events, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "events", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l132:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "events", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_params(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "params"));  if (!yy_LPAR(yy)) goto l141;  if (!yy_mkNil(yy)) goto l141;  yyDo(yy, yySet, -2, 0);
  {  int yypos142= yy->__pos, yythunkpos142= yy->__thunkpos;  if (!yy_id(yy)) goto l142;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_params, yy->__begin, yy->__end);
  l144:;	
  {  int yypos145= yy->__pos, yythunkpos145= yy->__thunkpos;  if (!yy_COMMA(yy)) goto l145;  if (!yy_id(yy)) goto l145;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_params, yy->__begin, yy->__end);  goto l144;
  l145:;	  yy->__pos= yypos145; yy->__thunkpos= yythunkpos145;
  }  goto l143;
  l142:;	  yy->__pos= yypos142; yy->__thunkpos= yythunkpos142;
  }
  l143:;	  if (!yy_RPAR(yy)) goto l141;  yyDo(yy, yy_3_params, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "params", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l141:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "params", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_id(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "id"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l146;
#undef yytext
#undef yyleng
  }  if (!yy_alpha(yy)) goto l146;
  l147:;	
  {  int yypos148= yy->__pos, yythunkpos148= yy->__thunkpos;  if (!yy_alnum(yy)) goto l148;  goto l147;
  l148:;	  yy->__pos= yypos148; yy->__thunkpos= yythunkpos148;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l146;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l146;  yyDo(yy, yy_1_id, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "id", yy->__buf+yy->__pos));
  return 1;
  l146:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "id", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_STATE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "STATE"));  if (!yymatchString(yy, "stt")) goto l149;  if (!yy__(yy)) goto l149;
  yyprintf((stderr, "  ok   %s @ %s\n", "STATE", yy->__buf+yy->__pos));
  return 1;
  l149:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STATE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_eol(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "eol"));  if (!yymatchClass(yy, (unsigned char *)"\000\044\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l150;
  yyprintf((stderr, "  ok   %s @ %s\n", "eol", yy->__buf+yy->__pos));
  return 1;
  l150:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eol", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_stmt(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 7, 0);
  yyprintf((stderr, "%s\n", "stmt"));
  {  int yypos152= yy->__pos, yythunkpos152= yy->__thunkpos;  if (!yy_PRINT(yy)) goto l153;  if (!yy_args(yy)) goto l153;  yyDo(yy, yySet, -7, 0);  if (!yy_SEMI(yy)) goto l153;  yyDo(yy, yy_1_stmt, yy->__begin, yy->__end);  goto l152;
  l153:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;  if (!yy_IF(yy)) goto l154;  if (!yy_LPAR(yy)) goto l154;  if (!yy_expr(yy)) goto l154;  yyDo(yy, yySet, -6, 0);  if (!yy_RPAR(yy)) goto l154;
  {  int yypos155= yy->__pos, yythunkpos155= yy->__thunkpos;  if (!yy_expr(yy)) goto l156;  yyDo(yy, yySet, -5, 0);  goto l155;
  l156:;	  yy->__pos= yypos155; yy->__thunkpos= yythunkpos155;  if (!yy_block(yy)) goto l154;  yyDo(yy, yySet, -5, 0);
  }
  l155:;	  if (!yy_ELSE(yy)) goto l154;
  {  int yypos157= yy->__pos, yythunkpos157= yy->__thunkpos;  if (!yy_expr(yy)) goto l158;  yyDo(yy, yySet, -4, 0);  goto l157;
  l158:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;  if (!yy_block(yy)) goto l154;  yyDo(yy, yySet, -4, 0);
  }
  l157:;	  yyDo(yy, yy_2_stmt, yy->__begin, yy->__end);  goto l152;
  l154:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;  if (!yy_IF(yy)) goto l159;  if (!yy_LPAR(yy)) goto l159;  if (!yy_expr(yy)) goto l159;  yyDo(yy, yySet, -6, 0);  if (!yy_RPAR(yy)) goto l159;
  {  int yypos160= yy->__pos, yythunkpos160= yy->__thunkpos;  if (!yy_block(yy)) goto l161;  yyDo(yy, yySet, -5, 0);  goto l160;
  l161:;	  yy->__pos= yypos160; yy->__thunkpos= yythunkpos160;  if (!yy_expr(yy)) goto l159;  yyDo(yy, yySet, -5, 0);
  }
  l160:;	  yyDo(yy, yy_3_stmt, yy->__begin, yy->__end);  goto l152;
  l159:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;  if (!yy_WHILE(yy)) goto l162;  if (!yy_LPAR(yy)) goto l162;  if (!yy_expr(yy)) goto l162;  yyDo(yy, yySet, -6, 0);  if (!yy_RPAR(yy)) goto l162;
  {  int yypos163= yy->__pos, yythunkpos163= yy->__thunkpos;  if (!yy_stmt(yy)) goto l164;  yyDo(yy, yySet, -5, 0);  goto l163;
  l164:;	  yy->__pos= yypos163; yy->__thunkpos= yythunkpos163;  if (!yy_block(yy)) goto l162;  yyDo(yy, yySet, -5, 0);
  }
  l163:;	  yyDo(yy, yy_4_stmt, yy->__begin, yy->__end);  goto l152;
  l162:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;  if (!yy_FOR(yy)) goto l165;  if (!yy_LPAR(yy)) goto l165;
  {  int yypos166= yy->__pos, yythunkpos166= yy->__thunkpos;  if (!yy_expr(yy)) goto l167;  yyDo(yy, yySet, -3, 0);  goto l166;
  l167:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;  if (!yy_mkFalse(yy)) goto l165;  yyDo(yy, yySet, -3, 0);
  }
  l166:;	  if (!yy_SEMI(yy)) goto l165;
  {  int yypos168= yy->__pos, yythunkpos168= yy->__thunkpos;  if (!yy_expr(yy)) goto l169;  yyDo(yy, yySet, -6, 0);  goto l168;
  l169:;	  yy->__pos= yypos168; yy->__thunkpos= yythunkpos168;  if (!yy_mkFalse(yy)) goto l165;  yyDo(yy, yySet, -6, 0);
  }
  l168:;	  if (!yy_SEMI(yy)) goto l165;
  {  int yypos170= yy->__pos, yythunkpos170= yy->__thunkpos;  if (!yy_expr(yy)) goto l171;  yyDo(yy, yySet, -4, 0);  goto l170;
  l171:;	  yy->__pos= yypos170; yy->__thunkpos= yythunkpos170;  if (!yy_mkFalse(yy)) goto l165;  yyDo(yy, yySet, -2, 0);
  }
  l170:;	  if (!yy_RPAR(yy)) goto l165;
  {  int yypos172= yy->__pos, yythunkpos172= yy->__thunkpos;  if (!yy_block(yy)) goto l173;  yyDo(yy, yySet, -5, 0);  goto l172;
  l173:;	  yy->__pos= yypos172; yy->__thunkpos= yythunkpos172;  if (!yy_expr(yy)) goto l165;  yyDo(yy, yySet, -5, 0);
  }
  l172:;	  yyDo(yy, yy_5_stmt, yy->__begin, yy->__end);  goto l152;
  l165:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;  if (!yy_RET(yy)) goto l174;
  {  int yypos175= yy->__pos, yythunkpos175= yy->__thunkpos;  if (!yy_expr(yy)) goto l176;  yyDo(yy, yySet, -1, 0);  goto l175;
  l176:;	  yy->__pos= yypos175; yy->__thunkpos= yythunkpos175;  if (!yy_mkFalse(yy)) goto l174;  yyDo(yy, yySet, -1, 0);
  }
  l175:;	  if (!yy_SEMI(yy)) goto l174;  yyDo(yy, yy_6_stmt, yy->__begin, yy->__end);  goto l152;
  l174:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;  if (!yy_STATE(yy)) goto l177;  if (!yy_id(yy)) goto l177;  yyDo(yy, yySet, -3, 0);  if (!yy_SEMI(yy)) goto l177;  yyDo(yy, yy_7_stmt, yy->__begin, yy->__end);  goto l152;
  l177:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;  if (!yy_expr(yy)) goto l178;  yyDo(yy, yySet, -1, 0);  if (!yy_SEMI(yy)) goto l178;  yyDo(yy, yy_8_stmt, yy->__begin, yy->__end);  goto l152;
  l178:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;  if (!yy__(yy)) goto l179;  if (!yy_SEMI(yy)) goto l179;  yyDo(yy, yy_9_stmt, yy->__begin, yy->__end);  goto l152;
  l179:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;  if (!yy_expr(yy)) goto l151;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_10_stmt, yy->__begin, yy->__end);
  }
  l152:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "stmt", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 7, 0);
  return 1;
  l151:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "stmt", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_define(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 5, 0);
  yyprintf((stderr, "%s\n", "define"));
  {  int yypos181= yy->__pos, yythunkpos181= yy->__thunkpos;  if (!yy_FUNC(yy)) goto l182;  if (!yy_id(yy)) goto l182;  yyDo(yy, yySet, -5, 0);  if (!yy_params(yy)) goto l182;  yyDo(yy, yySet, -4, 0);  if (!yy_block(yy)) goto l182;  yyDo(yy, yySet, -3, 0);  yyDo(yy, yy_1_define, yy->__begin, yy->__end);  goto l181;
  l182:;	  yy->__pos= yypos181; yy->__thunkpos= yythunkpos181;  if (!yy_id(yy)) goto l183;  yyDo(yy, yySet, -5, 0);  if (!yy_ASSIGN(yy)) goto l183;  if (!yy_assignment(yy)) goto l183;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_2_define, yy->__begin, yy->__end);  goto l181;
  l183:;	  yy->__pos= yypos181; yy->__thunkpos= yythunkpos181;  if (!yy_value(yy)) goto l180;  yyDo(yy, yySet, -1, 0);  if (!yy_index(yy)) goto l180;  yyDo(yy, yySet, -5, 0);  if (!yy_ASSIGN(yy)) goto l180;  if (!yy_assignment(yy)) goto l180;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_3_define, yy->__begin, yy->__end);
  }
  l181:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "define", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 5, 0);
  return 1;
  l180:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "define", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_state(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "state"));  if (!yy_STATE(yy)) goto l184;  if (!yy_id(yy)) goto l184;  yyDo(yy, yySet, -3, 0);  if (!yy_params(yy)) goto l184;  yyDo(yy, yySet, -2, 0);  if (!yy_events(yy)) goto l184;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_state, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "state", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l184:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "state", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy__(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "_"));
  l186:;	
  {  int yypos187= yy->__pos, yythunkpos187= yy->__thunkpos;  if (!yy_blank(yy)) goto l187;  goto l186;
  l187:;	  yy->__pos= yypos187; yy->__thunkpos= yythunkpos187;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_start(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "start"));
  {  int yypos189= yy->__pos, yythunkpos189= yy->__thunkpos;  if (!yy__(yy)) goto l190;  if (!yy_state(yy)) goto l190;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_start, yy->__begin, yy->__end);  goto l189;
  l190:;	  yy->__pos= yypos189; yy->__thunkpos= yythunkpos189;  if (!yy__(yy)) goto l191;  if (!yy_define(yy)) goto l191;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_start, yy->__begin, yy->__end);  goto l189;
  l191:;	  yy->__pos= yypos189; yy->__thunkpos= yythunkpos189;  if (!yy__(yy)) goto l192;  if (!yy_stmt(yy)) goto l192;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_3_start, yy->__begin, yy->__end);  goto l189;
  l192:;	  yy->__pos= yypos189; yy->__thunkpos= yythunkpos189;
  {  int yypos194= yy->__pos, yythunkpos194= yy->__thunkpos;  if (!yymatchDot(yy)) goto l194;  goto l193;
  l194:;	  yy->__pos= yypos194; yy->__thunkpos= yythunkpos194;
  }  yyDo(yy, yy_4_start, yy->__begin, yy->__end);  goto l189;
  l193:;	  yy->__pos= yypos189; yy->__thunkpos= yythunkpos189;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l188;
#undef yytext
#undef yyleng
  }
  l195:;	
  {  int yypos196= yy->__pos, yythunkpos196= yy->__thunkpos;
  {  int yypos197= yy->__pos, yythunkpos197= yy->__thunkpos;  if (!yy_eol(yy)) goto l197;  goto l196;
  l197:;	  yy->__pos= yypos197; yy->__thunkpos= yythunkpos197;
  }
  {  int yypos198= yy->__pos, yythunkpos198= yy->__thunkpos;  if (!yymatchDot(yy)) goto l196;  yy->__pos= yypos198; yy->__thunkpos= yythunkpos198;
  }  if (!yymatchDot(yy)) goto l196;  goto l195;
  l196:;	  yy->__pos= yypos196; yy->__thunkpos= yythunkpos196;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l188;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_5_start, yy->__begin, yy->__end);
  }
  l189:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "start", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l188:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "start", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_start);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 196 "./Parser/parser.leg"
;
void initLine(void)
{
	nlines = 0;
}

void initYYContext()
{
    yyrelease(yyctx);
}

#ifdef MSGC
void collectYYContext()
{
	if(yyctx){
		gc_markOnly(yyctx);
		// char     *__buf;
		// int       __buflen;
		gc_markOnly(yyctx->__buf);
		// int       __pos;
		// int       __limit;
		// char     *__text;
		// int       __textlen;
		gc_markOnly(yyctx->__text);
		// int       __begin;
		// int       __end;
		// int       __textmax;
		// yythunk  *__thunks;
		// int       __thunkslen;
		// int       __thunkpos;
		gc_markOnly(yyctx->__thunks);
// 		for(int i=0; i<yyctx->__thunkslen;i++){
// // typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;
// 			gc_markOnly(yyctx->__thunks[i].next)
// 			//action is function pointer
// 			//next is maybe not need ...
// 		}
		// YYSTYPE   __;
		// YYSTYPE  *__val;
		// YYSTYPE  *__vals;
		// int       __valslen;
		#undef yy
		#undef __
		gc_mark(yyctx->__);
		gc_mark(yyctx->__val);
		for(int i=0;i<yyctx->__valslen;i++){
			gc_mark(yyctx->__vals[i]);
		}
	}
}
#elif defined(MSGCS)
void collectYYContext()
{
	if(yyctx){
		gc_markOnly(yyctx);
		// char     *__buf;
		// int       __buflen;
		gc_markOnly(yyctx->__buf);
		// int       __pos;
		// int       __limit;
		// char     *__text;
		// int       __textlen;
		gc_markOnly(yyctx->__text);
		// int       __begin;
		// int       __end;
		// int       __textmax;
		// yythunk  *__thunks;
		// int       __thunkslen;
		// int       __thunkpos;
		gc_markOnly(yyctx->__thunks);
// 		for(int i=0; i<yyctx->__thunkslen;i++){
// // typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;
// 			gc_markOnly(yyctx->__thunks[i].next)
// 			//action is function pointer
// 			//next is maybe not need ...
// 		}
		// YYSTYPE   __;
		// YYSTYPE  *__val;
		// YYSTYPE  *__vals;
		// int       __valslen;
		#undef yy
		#undef __
		gc_mark(yyctx->__);
		gc_mark(yyctx->__val);
		for(int i=0;i<yyctx->__valslen;i++){
			gc_mark(yyctx->__vals[i]);
		}
	}
}
#else
   #error "GC is not defined, please define MSGC or MSGCS or add your own GC"
#endif // GC_SECTION

#endif // PARSER_H
